/* tslint:disable */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

/////////////////////////////////////////////////////////////////////////////
// Success Contract API
/////////////////////////////////////////////////////////////////////////////

export interface GetPrreviewsSuccessRootAPIResponseType {
  _links?: GetPrreviewsSuccessLinksAPIResponseType;
  author_association?: string;
  body?: string;
  commit_id?: string;
  html_url?: string;
  id?: number;
  node_id?: string;
  pull_request_url?: string;
  state?:
    | 'APPROVED'
    | 'CHANGES_REQUESTED'
    | 'COMMENTED'
    | 'PENDING'
    | 'DISMISSED';
  submitted_at?: string;
  user?: GetPrreviewsSuccessUserAPIResponseType;
}

interface GetPrreviewsSuccessLinksAPIResponseType {
  html?: GetPrreviewsSuccessHTMLAPIResponseType;
  pull_request?: GetPrreviewsSuccessHTMLAPIResponseType;
}

interface GetPrreviewsSuccessHTMLAPIResponseType {
  href?: string;
}

interface GetPrreviewsSuccessUserAPIResponseType {
  avatar_url?: string;
  events_url?: string;
  followers_url?: string;
  following_url?: string;
  gists_url?: string;
  gravatar_id?: string;
  html_url?: string;
  id?: number;
  login?: string;
  node_id?: string;
  organizations_url?: string;
  received_events_url?: string;
  repos_url?: string;
  site_admin?: boolean;
  starred_url?: string;
  subscriptions_url?: string;
  type?: string;
  url?: string;
  user_view_type?: string;
}

/////////////////////////////////////////////////////////////////////////////
// Error Contract API
/////////////////////////////////////////////////////////////////////////////

export interface GetPrreviewsErrorRootAPIResponseType {
  documentation_url?: string;
  message?: string;
  status?: string;
}

/////////////////////////////////////////////////////////////////////////////
// Root API
/////////////////////////////////////////////////////////////////////////////

export type GetPrreviewsRootAPIResponseType =
  | GetPrreviewsSuccessRootAPIResponseType[]
  | GetPrreviewsErrorRootAPIResponseType;
