/* eslint-disable */
/* tslint:disable */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

/////////////////////////////////////////////////////////////////////////////
// Success Contract API
/////////////////////////////////////////////////////////////////////////////

export interface GetPullrequestsSuccessRootAPIResponseType {
  _links?: GetPullrequestsSuccessLinksAPIResponseType;
  active_lock_reason?: null;
  assignee?: null;
  assignees?: GetPullrequestsSuccessUserAPIResponseType[];
  author_association?: string;
  auto_merge?: null;
  base?: GetPullrequestsSuccessBaseAPIResponseType;
  body?: string;
  closed_at?: null;
  comments_url?: string;
  commits_url?: string;
  created_at?: string;
  diff_url?: string;
  draft?: boolean;
  head?: GetPullrequestsSuccessBaseAPIResponseType;
  html_url?: string;
  id?: number;
  issue_url?: string;
  labels?: GetPullrequestsSuccessLabelAPIResponseType[];
  locked?: boolean;
  merge_commit_sha?: string;
  merged_at?: null;
  milestone?: null;
  node_id?: string;
  number?: number;
  patch_url?: string;
  requested_reviewers?: GetPullrequestsSuccessUserAPIResponseType[];
  requested_teams?: any[];
  review_comment_url?: string;
  review_comments_url?: string;
  state?: string;
  statuses_url?: string;
  title?: string;
  updated_at?: string;
  url?: string;
  user?: GetPullrequestsSuccessUserAPIResponseType;
}

interface GetPullrequestsSuccessLinksAPIResponseType {
  comments?: GetPullrequestsSuccessCommentsAPIResponseType;
  commits?: GetPullrequestsSuccessCommentsAPIResponseType;
  html?: GetPullrequestsSuccessCommentsAPIResponseType;
  issue?: GetPullrequestsSuccessCommentsAPIResponseType;
  review_comment?: GetPullrequestsSuccessCommentsAPIResponseType;
  review_comments?: GetPullrequestsSuccessCommentsAPIResponseType;
  self?: GetPullrequestsSuccessCommentsAPIResponseType;
  statuses?: GetPullrequestsSuccessCommentsAPIResponseType;
}

interface GetPullrequestsSuccessCommentsAPIResponseType {
  href?: string;
}

interface GetPullrequestsSuccessUserAPIResponseType {
  avatar_url?: string;
  events_url?: string;
  followers_url?: string;
  following_url?: string;
  gists_url?: string;
  gravatar_id?: string;
  html_url?: string;
  id?: number;
  login?: string;
  node_id?: string;
  organizations_url?: string;
  received_events_url?: string;
  repos_url?: string;
  site_admin?: boolean;
  starred_url?: string;
  subscriptions_url?: string;
  type?: GetPullrequestsSuccessTypeAPIResponseType;
  url?: string;
  user_view_type?: GetPullrequestsSuccessUserViewTypeAPIResponseType;
}

type GetPullrequestsSuccessTypeAPIResponseType =
  | 'GetPullrequestsSuccessUserAPIResponseType'
  | 'Organization';

type GetPullrequestsSuccessUserViewTypeAPIResponseType = 'public';

interface GetPullrequestsSuccessBaseAPIResponseType {
  label?: string;
  ref?: string;
  repo?: GetPullrequestsSuccessRepoAPIResponseType;
  sha?: string;
  user?: GetPullrequestsSuccessUserAPIResponseType;
}

interface GetPullrequestsSuccessRepoAPIResponseType {
  allow_forking?: boolean;
  archive_url?: string;
  archived?: boolean;
  assignees_url?: string;
  blobs_url?: string;
  branches_url?: string;
  clone_url?: string;
  collaborators_url?: string;
  comments_url?: string;
  commits_url?: string;
  compare_url?: string;
  contents_url?: string;
  contributors_url?: string;
  created_at?: string;
  default_branch?: string;
  deployments_url?: string;
  description?: string;
  disabled?: boolean;
  downloads_url?: string;
  events_url?: string;
  fork?: boolean;
  forks?: number;
  forks_count?: number;
  forks_url?: string;
  full_name?: string;
  git_commits_url?: string;
  git_refs_url?: string;
  git_tags_url?: string;
  git_url?: string;
  has_discussions?: boolean;
  has_downloads?: boolean;
  has_issues?: boolean;
  has_pages?: boolean;
  has_projects?: boolean;
  has_pull_requests?: boolean;
  has_wiki?: boolean;
  homepage?: null;
  hooks_url?: string;
  html_url?: string;
  id?: number;
  is_template?: boolean;
  issue_comment_url?: string;
  issue_events_url?: string;
  issues_url?: string;
  keys_url?: string;
  labels_url?: string;
  language?: string;
  languages_url?: string;
  license?: null;
  merges_url?: string;
  milestones_url?: string;
  mirror_url?: null;
  name?: string;
  node_id?: string;
  notifications_url?: string;
  open_issues?: number;
  open_issues_count?: number;
  owner?: GetPullrequestsSuccessUserAPIResponseType;
  private?: boolean;
  pull_request_creation_policy?: string;
  pulls_url?: string;
  pushed_at?: string;
  releases_url?: string;
  size?: number;
  ssh_url?: string;
  stargazers_count?: number;
  stargazers_url?: string;
  statuses_url?: string;
  subscribers_url?: string;
  subscription_url?: string;
  svn_url?: string;
  tags_url?: string;
  teams_url?: string;
  topics?: any[];
  trees_url?: string;
  updated_at?: string;
  url?: string;
  visibility?: string;
  watchers?: number;
  watchers_count?: number;
  web_commit_signoff_required?: boolean;
}

interface GetPullrequestsSuccessLabelAPIResponseType {
  color?: string;
  default?: boolean;
  description?: string;
  id?: number;
  name?: string;
  node_id?: string;
  url?: string;
}

/////////////////////////////////////////////////////////////////////////////
// Error Contract API
/////////////////////////////////////////////////////////////////////////////

export interface GetPullrequestsErrorRootAPIResponseType {
  documentation_url?: string;
  message?: string;
  status?: string;
}

/////////////////////////////////////////////////////////////////////////////
// Root API
/////////////////////////////////////////////////////////////////////////////

export type GetPullrequestsRootAPIResponseType =
  | GetPullrequestsSuccessRootAPIResponseType[]
  | GetPullrequestsErrorRootAPIResponseType;
